In [41]:
import pandas as pd
import numpy as np
from nltk.stem import WordNetLemmatizer
lemmatizer = WordNetLemmatizer()
pd.options.display.float_format = '{:,.0f}'.format

In [22]:
def lemma_maker(x, y):
    return lemmatizer.lemmatize(x,y)

In [26]:
br_to_us=pd.read_excel("Book.xlsx",skiprows=[0])
br_to_us_dict=dict(zip(br_to_us.UK.tolist(),br_to_us.US.tolist()))
spelling_replacement={'modifier':br_to_us_dict,'head':br_to_us_dict}

In [33]:
reddy11_study=pd.read_csv("/data/dharp/compounding/datasets/ijcnlp_compositionality_data/MeanAndDeviations.clean.txt",sep="\t")
#print(reddy11_study.columns)
reddy11_study.columns=['compound','to_divide']
reddy11_study['modifier_mean'],reddy11_study['modifier_std'],reddy11_study['head_mean'],reddy11_study['head_std'],reddy11_study['compound_mean'],reddy11_study['compound_std'],_=reddy11_study.to_divide.str.split(" ",7).str
reddy11_study['modifier'],reddy11_study['head']=reddy11_study['compound'].str.split(" ",2).str
reddy11_study.modifier=reddy11_study.modifier.str[:-2]
reddy11_study['head']=reddy11_study['head'].str[:-2]
reddy11_study.drop(['compound','to_divide'],axis=1,inplace=True)
reddy11_study['modifier']=np.vectorize(lemma_maker)(reddy11_study['modifier'],'n')
reddy11_study['head']=np.vectorize(lemma_maker)(reddy11_study['head'],'n')
reddy11_study.replace(spelling_replacement,inplace=True)
reddy11_study['modifier']=reddy11_study['modifier']+"_n"
reddy11_study['head']=reddy11_study['head']+"_n"
#reddy11_study.set_index(['modifier','head'],inplace=True)
reddy11_study

,modifier_mean,modifier_std,head_mean,head_std,compound_mean,compound_std,modifier,head
0,3.866667,1.117537,4.866667,0.339935,4.250000,0.871165,end_n,user_n
1,1.607143,1.654848,1.892857,1.496169,1.703704,1.717337,firing_n,line_n
2,2.821429,1.964935,4.862069,0.344828,3.827586,1.233693,game_n,plan_n
3,4.766667,0.422953,4.862069,0.344828,4.800000,0.476095,application_n,form_n
4,0.600000,0.800000,4.586207,1.099129,1.310345,1.020596,snail_n,mail_n
5,2.678571,1.691440,3.933333,1.181336,3.785714,1.205853,web_n,site_n
6,0.379310,0.805746,4.714286,0.839096,1.517241,1.133219,flea_n,market_n
7,0.428571,0.775913,5.000000,0.000000,2.642857,1.315139,grandfather_n,clock_n
8,1.066667,1.289272,3.407407,1.340516,1.703704,1.047566,diamond_n,wedding_n
9,4.714286,0.589015,0.862069,0.936764,2.185185,1.155888,guilt_n,trip_n
10,1.592593,1.472193,1.444444,1.770820,1.518519,1.449658,silver_n,spoon_n
11,3.107143,1.371633,2.862069,1.357588,3.333333,1.273665,rush_n,hour_n
12,2.000000,1.839732,4.620690,0.997023,3.851852,1.267944,china_n,clay_n
13,1.400000,1.083205,5.000000,0.000000,3.038462,1.224141,cocktail_n,dress_n
14,4.666667,0.537484,4.933333,0.249444,4.666667,0.471405,mailing_n,list_n
15,4.814815,0.771580,0.517241,1.037925,2.448276,1.248066,spelling_n,bee_n
16,4.666667,0.649786,4.766667,0.615540,4.400000,0.757188,public_n,service_n
17,2.931034,1.507019,4.517241,1.070633,4.000000,1.164965,head_n,teacher_n
18,4.500000,0.718795,5.000000,0.000000,4.600000,0.611010,video_n,game_n
19,4.666667,0.544331,0.413793,0.766418,2.275862,1.079481,spinning_n,jenny_n
20,3.961538,1.055417,0.466667,0.618241,2.038462,1.125945,think_n,tank_n
21,4.222222,1.065740,0.370370,0.727662,1.555556,1.099944,cash_n,cow_n
22,0.379310,0.611036,1.107143,1.144530,0.827586,0.912328,swan_n,song_n
23,0.666667,1.011050,1.851852,1.296825,0.724138,0.689655,monkey_n,business_n
24,0.370370,0.554320,0.814815,1.248318,0.750000,1.122020,snake_n,oil_n
25,0.714286,0.749149,1.000000,0.942809,0.714286,0.839096,smoking_n,gun_n
26,3.821429,0.888561,3.896552,0.959340,3.862069,1.007699,balance_n,sheet_n
27,0.758621,0.624509,4.607143,0.859372,1.250000,1.022078,zebra_n,crossing_n
28,0.884615,1.187335,1.730769,1.630424,1.250000,1.183970,cutting_n,edge_n
29,4.655172,0.956858,4.344828,0.799822,4.466667,0.718022,radio_n,station_n
...,...,...,...,...,...,...,...,...
60,0.296296,0.456623,0.448276,0.769514,0.310345,0.593264,gravy_n,train_n
61,3.655172,1.122677,4.666667,0.471405,3.700000,0.971253,case_n,study_n
62,4.466667,0.884433,0.500000,0.823754,1.925926,1.274419,night_n,owl_n
63,0.777778,0.916246,3.888889,1.396645,1.689655,0.875074,pecking_n,order_n
64,3.827586,1.052713,0.714286,0.749149,1.482759,1.102370,eye_n,candy_n
65,0.785714,0.976771,0.500000,0.866025,0.777778,0.874890,nest_n,egg_n
66,3.551724,1.220125,4.000000,1.032796,4.111111,1.065740,role_n,model_n
67,4.413793,1.067296,3.307692,2.071217,3.896552,1.422597,fashion_n,plate_n
68,0.185185,0.474305,3.785714,1.047348,1.250000,1.089725,crocodile_n,tear_n
69,0.250000,0.508850,2.035714,1.322393,0.857143,0.989743,rat_n,race_n
70,0.964286,0.944236,4.233333,0.919541,2.142857,1.273754,crash_n,course_n
71,0.642857,0.971534,1.551724,1.404088,1.428571,1.347712,rocket_n,science_n
72,4.750000,0.508850,0.714286,0.795395,2.166667,1.035482,memory_n,lane_n
73,1.035714,0.822980,4.896552,0.304543,2.320000,1.287478,smoking_n,jacket_n
74,4.344828,0.992241,4.689655,0.531974,4.571429,0.903508,interest_n,rate_n
75,4.862069,0.344828,5.000000,0.000000,4.931034,0.253395,engine_n,room_n
76,4.607143,0.672909,2.000000,1.281740,2.720000,0.917388,blame_n,game_n
77,3.733333,1.948219,3.866667,1.978776,3.724138,1.836349,brass_n,ring_n
78,0.500000,0.562731,4.655172,1.152983,1.807692,1.074861,panda_n,car_n
79,4.900000,0.300000,4.533333,0.956847,4.821429,0.382993,research_n,project_n
80,4.733333,0.442217,4.413793,0.720021,4.655172,0.657889,call_n,center_n
81,0.379310,0.611036,4.500000,0.718795,1.518519,1.166520,graveyard_n,shift_n
82,4.666667,0.537484,4.896552,0.304543,4.666667,0.699206,credit_n,card_n
83,2.300000,1.594783,4.000000,0.830455,2.892857,1.112888,cheat_n,sheet_n
84,4.833333,0.372678,4.766667,0.495536,4.700000,0.640312,parking_n,lot_n
85,3.172414,1.340843,2.033333,1.516209,2.689655,1.206404,fine_n,line_n
86,3.160000,2.203270,3.533333,1.857118,3.793103,1.749469,brick_n,wall_n
87,4.933333,0.249444,4.827586,0.377740,4.827586,0.460057,speed_n,limit_n
88,4.800000,0.400000,4.900000,0.300000,4.866667,0.339935,swimming_n,pool_n
89,4.866667,0.339935,4.827586,0.460057,4.733333,0.442217,bank_n,account_n

In [30]:
compounds=pd.read_csv("/data/dharp/compounding/datasets/compounds_reduced.csv",sep="\t",index_col=0)
#compounds=compounds.query('decade != 2000')
compounds=compounds.groupby(['modifier','head','decade'])['count'].sum().to_frame()
compounds=compounds.reindex()

                                       count
modifier        head           decade
a_n             aaaaa_n        1960        9
                               1970       10
                               1980        9
                               1990       14
                addison_n      1960       28
                               1970       96
                               1980      206
                               1990      196
                               2000      222
                anti_n         1960       27
                               1970       30
                               1980       41
                               1990       67
                               2000       90
                archive_n      1960       98
                               1970      258
                               1980       91
                               1990       60
                               2000       29
                atom_n         1940        9
                               1950       29
                               1960       34
                               1970       18
                               1980       14
                               1990       10
                               2000       25
                b_n            1800       18
                               1810       58
                               1820       74
                               1830      139
...                                      ...
zurich_n        seminar_n      2000      508
zwemmer_n       gallery_n      1960       32
                               1970       29
                               1980       36
                               1990       48
                               2000       74
zwinglische_n   reformation_n  1980       32
                               1990       55
                               2000       46
zwitterion_n    form_n         1970       14
                intermediate_n 1990      236
                mechanism_n    1990      118
                route_n        1990      228
zygapophyseal_n joint_n        1980       38
                               1990      281
                               2000      574
zygote_n        nucleus_n      1970       11
                result_n       1960       17
                               1970       14
                               1980       13
                               1990       15
                               2000       42
zygotene_n      stage_n        1960       18
                               1970       22
                               1980       31
                               1990       19
                               2000       12
zylobalsamum_n  process_n      1890       36
                               1920       10
                               2000       18

[4490479 rows x 1 columns]

In [48]:
temp_df=reddy11_study[['modifier','head']].merge(compounds.reset_index(),on=['modifier','head'],how='left')
#temp_df.set_index(['modifier','head','decade'],inplace=True)
temp_df=pd.pivot_table(temp_df,index=['modifier','head'],columns='decade',values='count',aggfunc=np.sum)
to_change=[str(x).split('.')[0] for x in temp_df.columns.tolist()]
temp_df.columns=to_change
temp_df

                          1800  1810  1820  1830  1840  1850  1860  1870  \
modifier      head
acid_n        test_n       nan   nan   nan   nan   nan   nan   nan   nan
application_n form_n       nan   nan   nan   nan   nan   nan   nan   nan
balance_n     sheet_n      nan   nan    56   259   367   919 1,084 1,755
bank_n        account_n    nan   nan    13    29    29    86   129   277
blame_n       game_n       nan   nan   nan   nan   nan   nan   nan   nan
brass_n       ring_n       nan    14    21   173    68    97   130   172
call_n        center_n     nan   nan   nan   nan   nan   nan   nan   nan
car_n         park_n       nan   nan   nan   nan   nan   nan   nan   nan
case_n        study_n      nan     9   nan   nan   nan   nan   nan   nan
cash_n        cow_n        nan   nan   nan   nan   nan   nan   nan   nan
chain_n       reaction_n   nan   nan   nan   nan   nan   nan   nan   nan
cheat_n       sheet_n      nan   nan   nan   nan   nan   nan   nan   nan
climate_n     change_n     nan   nan   nan   nan   nan   nan    18    11
cloud_n       nine_n       nan   nan   nan   nan   nan   nan   nan   nan
cocktail_n    dress_n      nan   nan   nan   nan   nan   nan   nan   nan
couch_n       potato_n     nan   nan   nan   nan   nan   nan   nan   nan
crash_n       course_n     nan   nan   nan   nan   nan   nan   nan   nan
credit_n      card_n       nan   nan   nan   nan   nan   nan   nan   nan
crocodile_n   tear_n       nan   nan    28    33    62    53    23    15
cutting_n     edge_n       nan   nan   nan    80   143   101   137   118
diamond_n     wedding_n    nan   nan   nan   nan   nan   nan   nan   nan
end_n         user_n       nan   nan   nan   nan   nan   nan   nan   nan
engine_n      room_n       nan   nan   nan    83    36    99   110   168
face_n        value_n      nan   nan   nan    10   nan    33    78   242
fashion_n     plate_n      nan   nan   nan   nan   nan    72   nan    11
fine_n        line_n       nan   nan   nan   nan   nan   nan   nan   nan
firing_n      line_n       nan   nan   nan   nan   nan   nan   nan   nan
game_n        plan_n       nan   nan   nan   nan   nan   nan   nan   nan
gold_n        mine_n        69   151   187   133   117   317   374   309
graduate_n    student_n    nan   nan   nan   nan   nan   nan   nan   nan
...                        ...   ...   ...   ...   ...   ...   ...   ...
memory_n      lane_n       nan   nan   nan   nan   nan   nan   nan   nan
monkey_n      business_n   nan   nan   nan   nan   nan   nan   nan   nan
night_n       owl_n        nan   nan     9    10   nan    15    12    15
parking_n     lot_n        nan   nan   nan   nan   nan   nan   nan   nan
pecking_n     order_n      nan   nan   nan   nan   nan   nan   nan   nan
polo_n        shirt_n      nan   nan   nan   nan   nan   nan   nan   nan
public_n      service_n     14    58    71   158   254   701   703   614
radio_n       station_n    nan   nan   nan   nan   nan    11   nan   nan
rat_n         race_n       nan   nan   nan   nan   nan   nan   nan   nan
research_n    project_n    nan   nan   nan   nan   nan   nan   nan   nan
rock_n        bottom_n     nan   nan   nan   nan   nan   nan   nan   nan
rocket_n      science_n    nan   nan   nan   nan   nan   nan   nan   nan
role_n        model_n      nan   nan   nan    10   nan   nan   nan   nan
rush_n        hour_n       nan   nan   nan   nan   nan   nan   nan   nan
sacred_n      cow_n        nan   nan   nan   nan   nan   nan   nan   nan
search_n      engine_n     nan   nan   nan   nan   nan   nan   nan   nan
silver_n      bullet_n      22    82   106   104    97   229   160   109
              screen_n     nan   nan   nan    28    16    20   nan    20
              spoon_n       73   198   146   286   525   971   744   830
smoking_n     gun_n        nan   nan   nan   nan   nan   nan   nan   nan
              jacket_n     nan   nan   nan   nan   nan   nan   nan   nan
snake_n       oil_n        nan   nan   nan   nan   nan   nan   nan   nan
speed_n       limit_n      nan   nan   nan   nan   nan   nan   nan   nan
spelling_n    bee_n        nan   nan   nan   nan   nan   nan   nan   nan
spinning_n    jenny_n      nan   nan   nan   nan   nan   nan   nan   nan
swan_n        song_n       nan   nan   nan   nan   nan   nan   nan     9
swimming_n    pool_n       nan   nan   nan   nan   nan   nan   nan   nan
think_n       tank_n       nan   nan   nan   nan   nan   nan   nan   nan
video_n       game_n       nan   nan   nan   nan   nan   nan   nan   nan
web_n         site_n        31   nan   nan   nan   nan   nan   nan   nan

                          1880  1890  ...   1910   1920   1930   1940   1950  \
modifier      head                    ...
acid_n        test_n        16    26  ...      9     10    nan     10     13
application_n form_n        57    87  ...    478    571    821  2,032  4,118
balance_n     sheet_n    2,020 4,637  ... 43,172 78,268 76,070 77,632 94,371
bank_n        account_n    553 1,371  ...  4,564  4,115  5,132  5,309  8,446
blame_n       game_n       nan   nan  ...    nan    nan    nan    nan    nan
brass_n       ring_n       173   179  ...    251    173    132    149    152
call_n        center_n     nan   nan  ...    nan    nan    nan    nan    nan
car_n         park_n       nan   nan  ...    nan    nan     70    159    445
case_n        study_n      nan     9  ...    264  2,243  9,568 11,474 29,932
cash_n        cow_n        nan   nan  ...    nan    nan    nan    nan    nan
chain_n       reaction_n   nan   nan  ...     69     78    657  7,060 21,994
cheat_n       sheet_n      nan   nan  ...    nan    nan    nan    nan    nan
climate_n     change_n     nan    16  ...    nan     10     14     35     70
cloud_n       nine_n       nan   nan  ...    nan    nan    nan    nan    nan
cocktail_n    dress_n      nan   nan  ...    nan    nan    nan    nan     68
couch_n       potato_n     nan   nan  ...    nan    nan    nan    nan    nan
crash_n       course_n     nan   nan  ...    nan    nan    nan    nan    nan
credit_n      card_n        60    96  ...    105    136     52    238    618
crocodile_n   tear_n        68    77  ...     71    204    136    221    257
cutting_n     edge_n       108   171  ...    217    162    242    406    485
diamond_n     wedding_n    nan   nan  ...    nan    nan    nan    nan    nan
end_n         user_n       nan   nan  ...    nan    nan    nan      9    101
engine_n      room_n       257   852  ...  4,012  3,161  2,209  3,529  3,521
face_n        value_n    1,567 4,431  ... 19,588 24,324 25,623 25,334 36,517
fashion_n     plate_n       42    16  ...     45     44     89     84    122
fine_n        line_n       nan   nan  ...    nan    nan    nan    nan    nan
firing_n      line_n       nan   nan  ...     92     95     80     91     71
game_n        plan_n       nan   nan  ...    nan    nan    nan    nan    nan
gold_n        mine_n       693   912  ...  1,213    851    883    759    839
graduate_n    student_n    nan    13  ...     92     99    114    146    484
...                        ...   ...  ...    ...    ...    ...    ...    ...
memory_n      lane_n       nan   nan  ...    nan    nan    nan    nan    nan
monkey_n      business_n   nan   nan  ...     25     34     82     88     89
night_n       owl_n         21    48  ...     27     43     72     36     39
parking_n     lot_n        nan   nan  ...    nan     19    244  1,592  4,788
pecking_n     order_n      nan   nan  ...    nan    nan    nan    nan     19
polo_n        shirt_n      nan   nan  ...    nan    nan     38     70     71
public_n      service_n  8,405 4,110  ... 26,894 28,556 27,857 23,173 39,216
radio_n       station_n     19    18  ...    476  2,664  3,826 10,104 12,677
rat_n         race_n       nan   nan  ...    nan    nan    nan    nan     13
research_n    project_n    nan    27  ...     20    592  2,733  5,435 15,366
rock_n        bottom_n      20    33  ...     96     62    109    131    313
rocket_n      science_n    nan   nan  ...    nan    nan    nan    nan    nan
role_n        model_n      nan   nan  ...    nan    nan    nan     25    190
rush_n        hour_n       nan   nan  ...    241    393    246    398    673
sacred_n      cow_n        nan   nan  ...    nan    nan    nan    nan    nan
search_n      engine_n     nan   nan  ...    nan    nan    nan    nan    nan
silver_n      bullet_n     304   297  ...    102    180    218    136    188
              screen_n     nan    56  ...     25     64    104    114     93
              spoon_n    1,398 1,373  ...  1,454  1,648  1,528  1,605  1,715
smoking_n     gun_n         13    51  ...     29     33     43     39     47
              jacket_n     nan   nan  ...     23     24     87     64    109
snake_n       oil_n        nan   nan  ...    nan    nan    nan    nan    nan
speed_n       limit_n      nan   nan  ...  1,339  1,270  1,296  1,504  2,909
spelling_n    bee_n        nan   nan  ...     61     42     26     87     95
spinning_n    jenny_n      nan   nan  ...      9    nan    nan    nan    nan
swan_n        song_n        70   136  ...     55     28     94     36     23
swimming_n    pool_n       nan    41  ...    347    613  1,009  1,506  2,558
think_n       tank_n       nan   nan  ...    nan    nan    nan    nan    nan
video_n       game_n       nan   nan  ...    nan    nan    nan    nan    nan
web_n         site_n        15    11  ...     21     85     43     33     53

                            1960    1970    1980    1990      2000
modifier      head
acid_n        test_n          49     805     900   1,429     1,955
application_n form_n       7,143  13,208  21,305  39,508    44,324
balance_n     sheet_n    136,029 172,020 281,296 447,042   659,867
bank_n        account_n   14,357  24,595  42,396  80,839   149,222
blame_n       game_n         nan       9      60     262     1,330
brass_n       ring_n         247     416     778   1,581     2,647
call_n        center_n       nan     nan     nan     235     2,741
car_n         park_n       2,163   5,189   9,575  18,792    37,262
case_n        study_n     79,411 216,616 390,239 737,327 1,258,029
cash_n        cow_n          nan     nan     291     628     1,286
chain_n       reaction_n  35,146  35,001  42,120  93,356   114,377
cheat_n       sheet_n        nan     nan     nan     570     3,428
climate_n     change_n       247   1,050   8,924 209,755   586,815
cloud_n       nine_n         nan      12      62      76       118
cocktail_n    dress_n        111     144     556   1,319     2,512
couch_n       potato_n       nan     nan      53     862     1,735
crash_n       course_n       242   1,672   4,632   8,903    16,766
credit_n      card_n       6,300  21,936  85,993 287,596   511,242
crocodile_n   tear_n         464     548     487     512       869
cutting_n     edge_n         723     894   1,002   1,123     1,573
diamond_n     wedding_n      nan      14      22      16        32
end_n         user_n         229   1,704  16,521  44,178   101,323
engine_n      room_n       5,383   5,175   7,283   9,653    20,166
face_n        value_n     62,020  78,090 109,842 170,613   229,304
fashion_n     plate_n        131     176     305     462       733
fine_n        line_n         nan     102     448     150       nan
firing_n      line_n         286     490     627     674       773
game_n        plan_n          48   1,053   2,995   7,437    15,497
gold_n        mine_n       1,296   1,384   1,703   2,654     4,039
graduate_n    student_n    1,339   2,989   4,014   7,500    11,845
...                          ...     ...     ...     ...       ...
memory_n      lane_n          15     121     506   2,000     5,842
monkey_n      business_n     141     182     253     300       469
night_n       owl_n          114      86     205     667     1,600
parking_n     lot_n       11,985  30,537  81,403 215,008   476,822
pecking_n     order_n        108     334     721   1,364     2,108
polo_n        shirt_n        210     487   1,382   4,411     9,943
public_n      service_n   70,777  86,801  80,580  83,721   106,339
radio_n       station_n   22,307  39,221  55,133  93,774   143,309
rat_n         race_n          57      98     148     273       397
research_n    project_n   46,074  93,543 140,721 203,108   305,574
rock_n        bottom_n       628   1,094   1,717   3,726     7,688
rocket_n      science_n      nan     nan      23   1,707    10,483
role_n        model_n      2,633  17,479  63,516 192,679   315,084
rush_n        hour_n       1,406   2,849   3,969   6,768    11,759
sacred_n      cow_n          nan     nan      78      40        40
search_n      engine_n        25      81     177  48,237   247,944
silver_n      bullet_n       285     424     407   1,718     7,497
              screen_n       213     396     973   2,192     4,214
              spoon_n      2,595   2,930   4,156   6,662    12,454
smoking_n     gun_n           43     165     554   1,356     5,302
              jacket_n       139     154     280     351       835
snake_n       oil_n           10     149     146     228       351
speed_n       limit_n      4,927   8,482  16,871  29,308    49,994
spelling_n    bee_n           73     176     499   1,529     1,591
spinning_n    jenny_n         39      45      27      57        44
swan_n        song_n          62     115      80      92       182
swimming_n    pool_n       5,804   8,451  20,576  41,070    49,207
think_n       tank_n          10     179     998   4,384    10,708
video_n       game_n         nan      21     857   2,938    25,067
web_n         site_n         215     881   2,534 256,503 1,364,228

[73 rows x 21 columns]